### ISSUE TITLE
Please add arm64 support

### ISSUE THREAD

**Issue by AArnott** [veler/CopyGitLink#22]
Odds are good you can do this just with a change to your `source.extension.vsixmanifest` file.

**Comment by veler** [comment]
That would be cool! Any way to test it without an ARM64 device?

**Comment by AArnott** [comment]
Yes, that might work. I have an arm64 device. If you send me the VSIX (or tell me where to download it from) I'll be happy to test it.

**Comment by veler** [comment]
Thanks @AArnott ! :)
Could you try this ZIP containing a VSIX inside by any chance?
[CopyGitLink.zip](https://github.com/veler/CopyGitLink/files/12053698/CopyGitLink.zip)

**Comment by AArnott** [comment]
Your vsix installed, but the copy link command that I'm used to seeing on amd64 machines doesn't show up on the arm64 machine I'm testing with.

**Comment by AArnott** [comment]
No, AnyCPU should be fine. Maybe I should attach a debugger and/or look at the logs to see if there are any silent failures.

**Comment by AArnott** [comment]
Never mind. It worked this time!

**Comment by veler** [comment]
Publishing :D

![image](https://github.com/veler/CopyGitLink/assets/3747805/723fcedf-6ac5-4c26-a236-a0633505cc86)
