### ISSUE TITLE
Not working on Worktrees

### ISSUE THREAD

**Issue by hanstzou** [veler/CopyGitLink#24]
CopyGitLink seems not working when using `git worktree`.

### Version
- [Copy Git Link 2022](https://marketplace.visualstudio.com/items?itemName=EtienneBAUDOUX.CopyGitLink2022): 1.4.5
- Visual Studio 2022: 17.11.5
- Windows 11: 23H2 (22631.4317)

### Steps to Reproduce

1. Clone a git repository: `git clone https://github.com/veler/CopyGitLink.git && cd CopyGitLink`
2. Add work tree: `git worktree add ../worktree`
3. In Visual Studio, open these two files for comparison:
    - `CopyGitLink\src\Impl\CopyGitLink\Core\CopyLinkService.cs`
    - `worktree\src\Impl\CopyGitLink\Core\CopyLinkService.cs`
4. Right click on source code

#### Expected
- Expect to see "Copy Link to Selection" for both files

#### Actual
- The file under `CopyGitLink` shows "Copy Link to Selection"
- The file under `worktree` does not

#### Screenshots
The left file is under `CopyGitLink` while the right under `worktree`.

<details>
<summary>Expand for screenshots</summary>
![clone](https://github.com/user-attachments/assets/8a39533b-aafe-4385-a1b5-28deb5562947)

![worktree](https://github.com/user-attachments/assets/26644d33-36af-4d0f-870a-3c6176bf3951)
</details>

**Comment by veler** [comment]
Hi,
Thanks for the feedback. For your information, Copy Git Link is now built-in in Visual Studio: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview?tabs=allfeatures#git-tooling

The in-box Copy Permalink works for worktrees as long as you have that worktree open in VS (it doesn't work with miscellaneous files).

Hope this help :)
